name: "<gradient:#2f2f2f:#ff3300><bold>Black Iron Clobberer</bold></gradient>"
lore:
  - "<dark_gray><italic>It hums with pressure, like a volcano sealed by will.</italic></dark_gray>"
  - "<red><italic>The longer it waits, the harder it strikes.</italic></red>"
  - ""
  - "<gold>▶ <bold>Hold sneak</bold> to charge vortex energy (up to 3 levels)</gold>"
  - "<gray>• Release to leap and dash forward</gray>"
  - "<gray>• If struck after dash, unleash a <red>stunning shockwave</red></gray>"
  - ""
  - "<dark_gray><italic>“It doesn't block hits. It returns them.”</italic></dark_gray>"
material: STICK
variables:
  var1:
    variableName: fall
    type: NUMBER
    default: 0.0
    isRefreshableClean: true
    refreshTagDoNotEdit: §他§天§生§他§生§天§地§道§心§心
  var0:
    variableName: charge
    type: NUMBER
    default: 0.0
    isRefreshableClean: true
    refreshTagDoNotEdit: §他§天§生§他§生§天§地§道§心§心
activators:
  activator0:
    option: LOOP
    detailedSlots:
      - -1
    commands:
      - SEND_MESSAGE %var_charge%
      - IF %var_charge%=0 score particles target:%player_uuid% shape:vortex points:5
        rate:25 time:40 color:WHITE,YELLOW
      - IF %var_charge%=1 score particles target:%player_uuid% shape:vortex points:5
        rate:25 time:40 color:YELLOW,ORANGE
      - IF %var_charge%>=2 score particles target:%player_uuid% shape:vortex points:5
        rate:25 time:40 color:ORANGE,RED
    playerConditions:
      ifSneaking: true
      ifSneakingMsg: ''
    delay: 2
    variablesModification:
      varUpdt0:
        variableName: charge
        type: MODIFICATION
        modification: 1.0
  activator1:
    option: PLAYER_DISABLE_SNEAK
    detailedSlots:
      - -1
    commands:
      - JUMP 2
      - DELAYTICK 26
      - DASH power:5 pitch:%player_pitch% yaw:%player_yaw%
    playerConditions:
      ifGameMode:
        - SURVIVAL
      ifGameModeMsg: '&4[ERROR] &cYou can''t activate the ability in Creative'
    placeholdersConditions:
      plchCdt0:
        type: PLAYER_NUMBER
        comparator: SUPERIOR_OR_EQUALS
        part1: '%var_charge%'
        part2: '2'
    variablesModification:
      varUpdt1:
        variableName: fall
        type: SET
        modification: 1.0
      varUpdt0:
        variableName: charge
        type: SET
        modification: 0.0
  activator2:
    option: PLAYER_RECEIVE_HIT_GLOBAL
    detailedSlots:
      - -1
    commands:
      - score particles target:%player_uuid% shape:explosionWave rate:7 height:1 offsetY:-1
        color:ORANGE,RED
      - MOB_AROUND distance:5 DAMAGE 2 <+> score particles target:%around_target_uuid%
        shape:vortex particle:ENCHANT points:5 rate:25 time:60 offsetY:2 <+> STUN_ENABLE
        <+> DELAY 3 <+> STUN_DISABLE
    placeholdersConditions:
      plchCdt0:
        type: PLAYER_NUMBER
        comparator: EQUALS
        part1: '%var_fall%'
        part2: '1'
    variablesModification:
      varUpdt1:
        variableName: fall
        type: SET
        modification: 0.0
blockAttacksFeatures:
  disableCooldownScale: 1.0
itemModel: ei:black_iron_clobberer
hiders:
  hideUsage: true