name: "<gradient:#00c3ff:#1e90ff><bold>Azure Sabre</bold></gradient>"
lore:
  - "<blue><italic>It glimmers like moonlight on calm waters,</italic></blue>"
  - "<aqua><italic>but strikes with the certainty of lightning.</italic></aqua>"
  - ""
  - "<gold>▶ <bold>Passive:</bold> Hidden blade in your off-hand</gold>"
  - "<gray>• <left_click> to strike swiftly</gray>"
  - "<gray>• Automatically slashes targets you hit</gray>"
  - ""
  - "<dark_gray><italic>“Beauty lies not in stillness, but in motion.”</italic></dark_gray>"
material: SHIELD
config_5: true
config_update: true
itemModel: ei:azure_sabre
hiders:
  hideUsage: true
activators:
  activator0:
    option: LOOP
    detailedSlots:
    - -1
    commands:
    - EQUIPMENT_VISUAL_REPLACE 40 EI:azure_sabre 1 20
  activator1:
    option: PLAYER_LEFT_CLICK
    typeTarget: NO_TYPE_TARGET
    cooldownFeatures:
      cooldown: 5
      isCooldownInTicks: true
      displayCooldownMessage: false
    detailedSlots:
    - -1
    commands:
    - DELAYTICK 5
    - SWING_OFF_HAND
  activator2:
    option: PLAYER_HIT_ENTITY
    detailedSlots:
    - -1
    commands:
    - DELAYTICK 5
    - SWING_OFF_HAND
    detailedEntities: []
    entityCommands:
    - DELAYTICK 8
    - DAMAGE 2
  activator3:
    option: PLAYER_HIT_PLAYER
    detailedSlots:
    - -1
    commands: []
    targetCommands:
    - DELAYTICK 5
    - DAMAGE 2
    - SWING_OFF_HAND
  activator4:
    option: PLAYER_DESELECT_THE_EI
    commands:
    - EQUIPMENT_VISUAL_CANCEL 40
    - EQUIPMENT_VISUAL_REPLACE 40 AIR 1 1
  activator5:
    option: PLAYER_SELECT_THE_EI
    commands:
    - EQUIPMENT_VISUAL_REPLACE 40 EI:azure_sabre 1 20
bannerSettings:
  patterns: {}
